"""LaTeX-rendered axis-label strings for ArqueoGal v1.4 figures."""

from __future__ import annotations

LABELS: dict[str, str] = {
    "Teff":       r"$T_\mathrm{eff}$ [K]",
    "logg":       r"$\log g$ [dex]",
    "Mh":         r"$\mathrm{[M/H]}$ [dex]",
    "FeH":        r"$\mathrm{[Fe/H]}$ [dex]",
    "alpha_M":    r"$\mathrm{[\alpha/M]}$ [dex]",
    "alpha_Fe":   r"$\mathrm{[\alpha/Fe]}$ [dex]",
    "MgH":        r"$\mathrm{[Mg/H]}$ [dex]",
    "numax":      r"$\nu_\mathrm{max}$ [$\mu$Hz]",
    "Dnu":        r"$\Delta\nu$ [$\mu$Hz]",
    "Lz":         r"$L_z$ [kpc km s$^{-1}$]",
    "Rgal":       r"$R_\mathrm{gal}$ [kpc]",
    "Z":          r"$Z$ [kpc]",
    "X":          r"$X$ [kpc]",
    "Y":          r"$Y$ [kpc]",
    "Vperp":      r"$V_\perp$ [km s$^{-1}$]",
    "VT_VLSR":    r"$V_T - V_\mathrm{LSR}$ [km s$^{-1}$]",
    "JR":         r"$J_R$ [kpc km s$^{-1}$]",
    "Jz":         r"$J_z$ [kpc km s$^{-1}$]",
    "JR_Jz":      r"$\sqrt{J_R + J_z}$ [(kpc km s$^{-1}$)$^{1/2}$]",
    "E":          r"$E$ [$10^5$ km$^2$ s$^{-2}$]",
    "Av":         r"$A_V$ [mag]",
    "pull":       r"pull $= (\hat{y} - y) / \hat{\sigma}$",
    "dM_pct":     r"$d_M$ percentile",
    "wavelength": r"wavelength [nm]",
    "flux_norm":  r"flux / band-median",
    "amp_norm":   r"normalised amplitude",
    "hermite_idx": r"Hermite coefficient index",
    "epoch":      r"epoch",
    "loss":       r"loss",
    "rmse_ratio": r"val RMSE / val RMSE($t = 0$)",
    "pull_width": r"pull width",
    "rmse_apg":   r"RMSE / APOGEE DR19 floor",
    "frac_pct":   r"fraction of holdout (%)",
    "counts_log": r"counts (log)",
    "Mahal_pct":  r"Mahalanobis percentile",
    "xp_M_pct":   r"XP-Mahalanobis percentile",
    "lab_M_pct":  r"label-Mahalanobis percentile",
    "lon":        r"Galactic longitude [deg]",
    "lat":        r"Galactic latitude [deg]",
}
